Integrador_Reserva/Controllers/publicoController.cs
using Integrador_Reserva.Models;
using Integrador_Reserva.Sources.Entities;
using Integrador_Reserva.Sources.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Integrador_Reserva.Controllers
{
    public class publicoController : Controller
    {
        // GET: publico
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RegistroReserva()
        {
            return View();
        }

        public ActionResult TerminosYCondiciones()
        {
            return View();
        }

        public ActionResult ResultadoBusqueda(UsuarioCanchaViewModel objUCVM)
        {
            UsuarioBusinessLogic uBL = new UsuarioBusinessLogic();
            UsuarioCanchaViewModel objUsuarioCancha = new UsuarioCanchaViewModel();
            objUsuarioCancha.cancha = new Cancha();
            objUsuarioCancha.cancha.cancha_distrito_id = objUCVM.cancha.cancha_distrito_id;
            if (objUCVM.cancha.cancha_distrito == null)
            {
                objUsuarioCancha.cancha.cancha_distrito = "";
            }
            else
            {
                objUsuarioCancha.cancha.cancha_distrito = objUCVM.cancha.cancha_distrito;
            }

            objUsuarioCancha.listaCancha = uBL.ListaCanchasxSearch(objUsuarioCancha.cancha);
            return View(objUsuarioCancha);
        }

        public ActionResult busqueda(UsuarioCanchaViewModel objUCVM)
        {
            return View(objUCVM);
        }

        public ActionResult RegistroCliente()
        {
            UsuarioCanchaViewModel objUsuarioCancha = new UsuarioCanchaViewModel();
            objUsuarioCancha.usuario = new Usuario();
            return View(objUsuarioCancha);
        }

        [HttpPost]
        public ActionResult RegistroCliente(UsuarioCanchaViewModel obj)
        {
            UsuarioBusinessLogic usuarioBusinessLogic = new UsuarioBusinessLogic();
            UsuarioCanchaViewModel objUsuarioCancha = obj;
            if (ModelState.IsValid)
            {
                string msg = new UsuarioBusinessLogic().registrarUsuario(objUsuarioCancha.usuario);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult AñadirCancha()
        {
            UsuarioBusinessLogic usuarioBusinessLogic = new UsuarioBusinessLogic();
            UsuarioCanchaViewModel objUsuarioCancha = new UsuarioCanchaViewModel();
            objUsuarioCancha.usuario = new Usuario();
            objUsuarioCancha.cancha = new Cancha();
            objUsuarioCancha.usuario.usuario_id = 1;
            objUsuarioCancha.usuario.usuario_nombre = "controlador";
            objUsuarioCancha.usuario.usuario_razonsocial = "controlador.SAC";
            objUsuarioCancha.cancha.cancha_usuario_id = 1;
            objUsuarioCancha.listaTipos = usuarioBusinessLogic.listaTipo();
            objUsuarioCancha.listaDistritos = usuarioBusinessLogic.listaDistrito();
            objUsuarioCancha.listaServicios = usuarioBusinessLogic.listaServicio();

            return View(objUsuarioCancha);
        }




        [HttpPost]
        public ActionResult AñadirCancha(UsuarioCanchaViewModel objUCVM, HttpPostedFileBase file)
        {

            if (file != null)
            {

                string archivo = (file.FileName).ToLower();
                string prefijo = DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + objUCVM.cancha.cancha_nombre;
                string pic = System.IO.Path.GetFileName(file.FileName).ToLower();
                string ext = System.IO.Path.GetExtension(pic);
                string path = System.IO.Path.Combine(
                    Server.MapPath("~/Sources/img/") + prefijo + "_" + pic);
                bool msj;

                if (ext == ".png" || ext == ".jpg")
                {
                    msj = true;
                }
                else { msj = false; }
                objUCVM.cancha.cancha_ImagenUrl = (msj) ? prefijo + "_" + pic : "image_no_found.png";
                objUCVM.cancha.cancha_usuario_id = 1;
                string msg = String.Empty;

                if (ModelState.IsValid)
                {
                    msg = new UsuarioBusinessLogic().registrarCancha(objUCVM.cancha);
                    file.SaveAs(path);
                }

            }


            return RedirectToAction("Index", "Home");
        }

        public ActionResult VerCalendarioCancha(int idCancha)
        {
            UsuarioBusinessLogic usuarioBusinessLogic = new UsuarioBusinessLogic();
            CalendarioViewModel oCalendarioViewModel = new CalendarioViewModel();
            oCalendarioViewModel.Cancha = usuarioBusinessLogic.ObtenerCanchaPorID(idCancha);
            //Lo siguiente obtener de BD, enviándole el idCancha
            //oCalendarioViewModel.Cancha.cancha_id = idCancha;
            //oCalendarioViewModel.Cancha.cancha_descripcion = "La mejor cancha de Lima";
            //oCalendarioViewModel.Cancha.cancha_distrito = "Lince";
            //oCalendarioViewModel.Cancha.cancha_nombre = "La Bombonera";
            //oCalendarioViewModel.Cancha.cancha_tipo = "6x6";
            //oCalendarioViewModel.Cancha.Precio = 160;
            //oCalendarioViewModel.Cancha.UrlImagen = "2.jpg";
            oCalendarioViewModel.Cliente = new Cliente();
            oCalendarioViewModel.Reserva = new Reserva();

            return View(oCalendarioViewModel);
        }

        public JsonResult GetDiaryEvents(int? cancha_id, string start, string end)
        {
            UsuarioBusinessLogic uBL = new UsuarioBusinessLogic();
            if (!String.IsNullOrWhiteSpace(start) && !String.IsNullOrWhiteSpace(end))
            {
                start = start.Replace("-", "");
                end = end.Replace("-", "");
            }

            List<DiaryEvent> listaEventos = uBL.Obtiene_Reservas_New(cancha_id, start, end);
            var eventList = from e in listaEventos
                            select new
                            {
                                id = e.IdReserva,
                                title = e.Title + " - " + e.ClienteNombre,
                                ClienteNombre = e.ClienteNombre,
                                start = e.StartDateString,
                                end = e.EndDateString,
                                IdCancha = e.IdCancha.ToString(),
                                IdEstado = e.IdEstado.ToString(),
                                color = Convert.ToDateTime(e.EndDateString) < DateTime.Now ? "#FF8000" : "",
                                editable = e.Editar,
                                allDay = false
                            };
            var rows = eventList.ToArray();
            return Json(rows, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarReserva(CalendarioViewModel oCalendarioViewModel)
        {
            string msg = String.Empty;
            //if (ModelState.IsValid)
            //{
            msg = new UsuarioBusinessLogic().GuardarReserva(oCalendarioViewModel);
            //}
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
    }
}

Integrador_Reserva/Views/publico/AñadirCancha.cshtml
@model Integrador_Reserva.Models.UsuarioCanchaViewModel
@{
    ViewBag.Title = "AñadirCancha";
}
<style>
    sup {
        color: #F05353;
        font-size: 14px;
        top: -1px;
        left: 2px;
    }
</style>
<br /><br /><br />
<div>
    <img src="http://www.forumlibertas.com/wp-content/uploads/2017/04/futbol-2000x1218-710x434.jpg" width="100%" height="350" class="alert-success" />
</div>
@using (Html.BeginForm("AñadirCancha", "Publico", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frm-anadirCancha", @class = "well" }))
{
    <center><h2>Registra tu Cancha</h2></center>
    <div>
        <form class="form-horizontal">
            <fieldset>
                <div class="row" style="margin-bottom:15px;">
                    <div class="col-md-4">
                        <label for="name">Nombre Cancha<sup>*</sup></label>
                        @Html.TextBoxFor(cancha => cancha.cancha.cancha_nombre,
                                new
                                {
                                    @class = "form-control input-md",
                                    @placeholder = "Ingrese el nombre de la cancha",
                                    @Value = "",
                                    @required = ""
                                })
                    </div>
                    <!-- Text input-->
                    <div class="col-md-4">
                        <label for="name">Distrito<sup>*</sup></label>
                        @Html.DropDownListFor(cancha => cancha.cancha.cancha_distrito_id,
                                new SelectList(Model.listaDistritos, "distrito_id", "distrito"),
                                new { @class = "form-control input-md" })
                    </div>

                    <!-- precio-->
                    <div class="col-md-4">
                        <label for="Costo">Costo<sup>*</sup> </label>
                        @Html.TextBoxFor(cancha => cancha.cancha.cancha_PrecioxHora,
                            new
                            {
                                @class = "form-control input-md",
                                @placeholder = "Ingrese el precio",
                                @Value = "",
                                @required = ""
                            })
                    </div>
                </div>
                <div class="row" style="margin-bottom:15px;">
                    <!--Tipo de Cancha -->
                    <div class="col-md-4">
                        <label for="selectbasic">Tipo Cancha<sup>*</sup></label>
                        @Html.DropDownListFor(cancha => cancha.cancha.cancha_tipo_id,
                            new SelectList(Model.listaTipos, "tipo_id", "tipo"),
                            new { @class = "form-control" })
                    </div>
                    <!--Descripcion de Cancha -->
                    <div class="col-md-4">
                        <label for="selectbasic">Descripción de la Cancha<sup>*</sup></label>
                        @Html.TextBoxFor(cancha => cancha.cancha.cancha_descripcion,
                                new
                                {
                                    @class = "form-control input-md",
                                    @placeholder = "Ingrese breve descripción",
                                    @Value = "",
                                    @required = ""
                                })
                    </div>
                    <!--Imagen -->
                    <div class="col-md-4">
                        <label for="imagen">Imagen <sup>*</sup></label>
                        <input id="imagen" name="file" class="input-file" type="file" required="">
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-5">
                            <button id="save" name="guardar" class="btn btn-primary">Registrar</button>
                            <button id="cancel" name="cancelar" class="btn btn-warning">Cancelar</button>
                        </div>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
}
<div class="samp">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <p style="font-family:Cambria;">
        <h4><b>*Terminos y Condiciones</b></h4>
        Todas las ventas son en firme y no se realizaran anulaciónes, reembolsos o
        cambios de fecha u horario de la reserva una vez que se haya confirmado su orden.
        Si hay un aplazamiento de fecha o cambio de hora del evento, por una razón inherente al Comité,
        el encargado de la cancha efectuará el reporte correspondiente al administrador autorizado por LDA;
        para valorar la asignación de un nuevo horario de uso, en dependencia de la disponibilidad existente,
        el cual será comunicado al cliente por la vía telefónica. LDA;, por razones de fuerza mayor o de interés
        público, tiene la facultad de cancelar cualquier reservación y efectuar el reembolso o reprogramación
        correspondiente, siempre y cuando lo haga en un plazo no mayor a 72 horas antes del servicio programado.
    </p>
</div>

Integrador_Reserva/Views/publico/RegistroCliente.cshtml
@model Integrador_Reserva.Models.UsuarioCanchaViewModel

@{
    ViewBag.Title = "RegistroCliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    sup {
        color: #F05353;
        font-size: 14px;
        top: -1px;
        left: 2px;
    }
</style>
<div class="container">
    <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Registro de Cliente</div>
            </div>
            <div class="panel-body">

@using (Html.BeginForm("RegistroCliente", "publico", FormMethod.Post, new { @id = "frm-anadirUsuario", @class = "well" }))
{

                    <div id="div_id_username" class="form-group required">
                        <label for="id_username" class="control-label col-md-4  requiredField">
                            Nombre
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_nombre,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese su nombre completo",
                 @Value = "",
                 @required = "",
                 @style = "margin-bottom: 10px"

             })
                        </div>
                    </div>

                    <div id="div_id_password1" class="form-group required">
                        <label for="id_password1" class="control-label col-md-4  requiredField">
                            Contraseña
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.PasswordFor(usuario => usuario.usuario.usuario_contraseña,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese una contraseña",
                 @required = "",
                 @style = "margin-bottom: 10px"

             })
                        </div>
                    </div>

                    <div id="div_id_username" class="form-group required">
                        <label for="id_username" class="control-label col-md-4  requiredField">
                            Razon Social
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_razonsocial,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese su razon social",
                 @required = "",
                 @style = "margin-bottom: 10px"
             })
                        </div>
                    </div>

                    <div id="div_id_email" class="form-group required">
                        <label for="id_email" class="control-label col-md-4  requiredField">
                            RUC
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_ruc,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese su número de RUC",
                 @required = "",
                 @style = "margin-bottom: 10px"
             })
                        </div>
                    </div>

                    <div id="div_id_email" class="form-group required">
                        <label for="id_email" class="control-label col-md-4  requiredField">
                            E-mail
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_email,
             new
             {
                 @class = "form-control input-md emailinput",
                 @placeholder = "Ingrese su email",
                 @required = "",
                 @style = "margin-bottom: 10px"
             })
                        </div>
                    </div>

                    <div id="div_id_number" class="form-group required">
                        <label for="id_number" class="control-label col-md-4  requiredField">
                            Télefono
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_telefono,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese su telefono",
                 @required = "",
                 @style = "margin-bottom: 10px"
             })
                        </div>
                    </div>

                    <div id="div_id_name" class="form-group required">
                        <label for="id_name" class="control-label col-md-4  requiredField">
                            Presentación<span class="asteriskField">*</span>
                        </label>
                        <div class="controls col-md-8 ">
                            @Html.TextBoxFor(usuario => usuario.usuario.usuario_presentacion,
             new
             {
                 @class = "form-control input-md textinput textInput",
                 @placeholder = "Ingrese una presentación",
                 @required = "",
                 @style = "margin-bottom: 10px"
             })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="aab controls col-md-4 "></div>
                        <div class="controls col-md-8 ">
                            <button type="submit" id="registrar" name="registrar" class="btn btn-success">Registrar</button>

                        </div>
                    </div>
}
                
            </div>
        </div>
    </div>
</div>

Integrador_Reserva/Views/publico/RegistroReserva.cshtml
@{
    ViewBag.Title = "RegistroReserva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RegistroReserva</h2>
<form action="/Home/Index" method="post" id="formRegistroReserva">
    <div class="container-fluid">
        <section class="container">
            <div class="container-page">
                <div class="col-md-6">

                    <div class="form-group col-lg-12">
                        <h3 class="dark-grey">Datos de la Reserva</h3>
                        <p>
                            Cancha: la canchita
                        </p>
                        <p>
                            Tipo: 6x6
                        </p>
                        <p>
                            Servicios: estacionamiento, Bodega, Duchas
                        </p>
                        <p>
                            Turno: 10 am - 11 am
                        </p>
                        <p>
                            Día: 02 de agosto de 2017
                        </p>
                        <p>
                            Precio: $ 15.00
                        </p>
                        <br />
                    </div>
                    <h3 class="dark-grey">Datos del Cliente</h3>

                    <div class="form-group col-lg-12">
                        <label>Nombre</label>
                        <input type="text" name="" class="form-control" id="nombre" value="">
                    </div>

                    <div class="form-group col-lg-5">
                        <label>Celular</label>
                        <input type="number" name="" class="form-control" id="celular" value="" maxlength="9">
                    </div>

                    <div class="form-group col-lg-7">
                        <label>Email Address</label>
                        <input type="email" name="" class="form-control" id="email" value="">
                    </div>

                    <div class="col-sm-6">
                        <input type="checkbox" class="checkbox" id="visibilidad"/>Permitir visibilidad de reserva al publico
                    </div>

                    <div class="col-sm-6">
                        <input type="checkbox" class="checkbox" id="invitacion"/>Recibir invitaciones para campeonatos
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group col-lg-12">
                        <h3 class="dark-grey">Terminos en Condiciones</h3>
                        <p>Estimado cliente,</p>
                        <p>
                            <b>sasd</b>
                            A través de nuestro servicio de reservas on line usted está contratando la
                            reserva de centros deportivos. El usuario comprende y acepta las siguientes condiciones:
                        </p>
                        <p>
                            • Este servicio está dirigido a personas con la capacidad legal necesaria para contratar
                            los servicios ofrecidos en ésta página web.
                        </p>
                        <p>
                            • El cliente/usuario es responsable de la veracidad de los datos introducidos a la
                            hora de realizar una reserva, DEPORTE ONLINE no se hace responsable de las consecuencias
                            derivadas de una introducción falsa o errónea de los datos.
                        </p>
                        <p>• La reserva se efectua con un plazo de 48 horas de anticipación</p>
                        <p>• Al efectuar la reserva el cliente tiene un plazo de 48 horas para realizar el pago y completar el proceso de reserva</p>
                        <p>
                            • En caso de cancelar una reserva, el cliente debe realizarlo 24 horas antes del dia
                            fijado en la reserva para la correspondiente devolucion del pago
                        </p>
                        <p></p>
                    </div>

                    <div class="form-group col-lg-12">
                        <h3 class="dark-grey">Formas de Pago</h3>
                        <div class="col-sm-2">
                            Efectivo
                        </div>
                        <div class="col-sm-7">
                            Visa - Mastercard
                        </div>

                        <div class="col-sm-6">
                            cta BBVA : 110100203010
                        </div>
                        <div class="col-sm-6">
                            cta BCP : 1011012111099
                        </div>

                    </div>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </div>
        </section>
    </div>
</form>

Integrador_Reserva/Views/publico/ResultadoBusqueda.cshtml
@model Integrador_Reserva.Models.UsuarioCanchaViewModel
@{
    ViewBag.Title = "Resultado Busqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <h2 class="text-center">Resultado de búsqueda</h2>
        <hr />
        <strong>Se encontró @Html.Label(Model.listaCancha.Count.ToString()) resultado(s)</strong>
    </div>
    <div class="row">
        
        @foreach (var x in Model.listaCancha)
        { 
            <div class="col-sm-6 col-md-5">
                <div class="thumbnail">
                    <h4>
                        @Html.DisplayFor(a => x.cancha_nombre)
                        <span class="label label-info info" style="float:right">
                            <span data-toggle="tooltip" title="Distrito">@Html.DisplayFor(a => x.cancha_distrito) <b class="glyphicon glyphicon-eye-open"></b></span>
                            <span data-toggle="tooltip" title="Tipo de cancha">@Html.DisplayFor(a => x.cancha_tipo) <b class="glyphicon glyphicon-inbox"></b></span>                            
                        </span>
                    </h4>
                    <img src="~/Sources/img/@Html.DisplayFor(a => x.cancha_ImagenUrl)" style="width:500px; height:350px; " />
                    <a href="@Url.Action("VerCalendarioCancha", null, new { idCancha = x.cancha_id, controller = "publico" }, Request.Url.Scheme)" class="btn btn-primary col-xs-12" role="button">Reservar</a>
                   
                    <div class="clearfix"></div>
                </div>
            </div>
        }
        
    </div>
</div>

Integrador_Reserva/Views/publico/busqueda.cshtml
@{
    ViewBag.Title = "busqueda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}